cloneConcurrency: 8
defaultSemverRangePrefix: "~"
enableScripts: false
enableTelemetry: false
httpRetry: 3
httpTimeout: 60000
nmMode: classic
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.1.1.cjs
compressionLevel: mixed
